version: "2"
services:
  pantryclient:
    container_name: pantryclient
    restart: always
    build: ./frontend
    ports:
      - "5100:5100"
    links:
      - pantryapp
  pantryapp:
    container_name: pantryapp
    restart: always
    build: ./backend
    ports:
      - "4100:4100"
    depends_on:
      - mongo
  mongo:
    container_name: pantrymongo
    image: mongo
    restart: always
    expose:
      - "27117"
    volumes:
      - ./data:/data/pantrydb
    ports:
      - "27117:27117"